### ISSUE TITLE
rabbit(Documentação): Estudar a Documentação

### ISSUE THREAD

**Issue by fdiogo1** [unb-mds/2024-2-Amaiszonia#10]

**Comment by GuilhermeDavila** [comment]
# Na documentação iremos colocar:
- Informações sobre o que é o projeto  
- Os colaboradores  
- Um resumo dos temas e decisões das reuniões semanais  
- Documentação sobre a API (caso tenhamos uma)  
- Arquitetura de software 
- Identidade visual
