### ISSUE TITLE
Jigsaw(StoryMap): Estudar e criar o StoryMap

### ISSUE THREAD

**Issue by fdiogo1** [unb-mds/2024-2-Amaiszonia#11]

**Comment by fdiogo1** [comment]
## StoryMap
É uma representação visual que mapeia as histórias de usuário (user stories) em um formato estruturado e sequencial. Ele mostra a jornada do usuário ao interagir com o produto, destacando os principais passos ou tarefas e as funcionalidades que devem ser implementadas para atendê-las.

### Estrutura básica de um StoryMap:
- **Linha horizontal (Jornada do Usuário):**
  - Representa as _atividades_ ou _etapas principais_ que o usuário realiza ao usar o produto.
  - Exemplo: "Cadastrar-se", "Pesquisar produto", "Finalizar compra".
- **Linha vertical (Prioridades):**
  - Contém as histórias de usuário associadas a cada etapa da jornada, organizadas por prioridade (de cima para baixo).
  - Exemplo: "Como um usuário, eu quero receber um e-mail de confirmação após o cadastro".
- **Divisão por releases (opcional):**
  - As funcionalidades podem ser organizadas em grupos de entregas (releases) ou sprints, permitindo uma visão clara do que será entregue em cada fase.
---
### Benefícios do StoryMap em um projeto:
- **Foco no usuário:** Garante que as funcionalidades desenvolvidas atendam às necessidades reais do usuário.
- **Planejamento colaborativo:** Ajuda a equipe a alinhar esforços e entender o fluxo do produto.
- **Priorização eficiente:** Destaca as funcionalidades mais críticas, permitindo um desenvolvimento incremental.
- **Visão geral do projeto:** Fornece um mapa claro de como as partes do sistema se _conectam_ e _evoluem_.

**Comment by bigkaio** [comment]
## StoryMap
 * Após analisar como será exeutado o projeto criamos o storymap seguindo todos os requisitos necessários, clique [aqui](https://miro.com/welcomeonboard/WStDb05BRWxVdUlOYW8xRzY3VGFmK0kvRG1FejVYRnE4czJqdHlDazBGNFkvMVBLMDZ6RXQxemdSNEkweU5TZmRyYTRISGIvbVc0ei93ZkVuWG9QYkFpNW85clp5MjdFNmRHNTkyM1pBS0ZxZjk4ZittV0srcGVHZ2lKU2VnNnUhZQ==?share_link_id=264935377729) para visualizar o produto final
