### ISSUE TITLE
Estudar e criar protótipo de arquitetura

### ISSUE THREAD

**Issue by fdiogo1** [unb-mds/2024-2-Amaiszonia#12]

**Comment by bigkaio** [comment]
# Protótipo de arquitetura
Foi realizado os estudos sobre a arquitetura do projeto e dessa forma foi criado o protótipo de arquitetura que pode ser encontrada tanto no readme.md como no link:
https://www.figma.com/design/Qwr0wSu0u54PdgBDXFdI1A/Prot%C3%B3tipo-de-Arquitetura?node-id=0-1&node-type=canvas&t=OBFGqpgMIYJd15s8-0
