### ISSUE TITLE
 rabbit (Figma): estudo sobre a ferramenta Figma 

### ISSUE THREAD

**Issue by fdiogo1** [unb-mds/2024-2-Amaiszonia#3]

**Comment by renanpariiz** [comment]
# Figma: Ferramenta de Design e Prototipação Baseada na Nuvem

O Figma é uma ferramenta de design amplamente utilizada para prototipação de software. Ele permite que equipes colaborem em tempo real, facilitando o desenvolvimento de interfaces de usuário (UI) e experiências de usuário (UX).

## 1. Colaboração em Tempo Real
- **Multiplataforma**: Funciona diretamente no navegador, mas também possui aplicativos desktop.
- **Trabalho em Equipe**: Vários usuários podem editar o mesmo projeto simultaneamente, com mudanças visíveis em tempo real.

## 2. Ferramentas de Design
- **Componentes Reutilizáveis**: Criação de botões, menus e outros elementos que podem ser replicados e atualizados globalmente.
- **Bibliotecas de Estilos**: Permite centralizar cores, tipografias e outros estilos, garantindo consistência visual.

## 3. Funcionalidades de Prototipação
- **Links Interativos**: Facilita a criação de fluxos navegacionais, simulando transições entre telas.
- **Animações e Transições**: Possibilita a inclusão de animações para enriquecer a experiência do usuário.
- **Teste de Usuário**: Permite compartilhar protótipos para que stakeholders ou usuários testem a navegação.

## 4. Integrações
- **Ferramentas de Desenvolvimento**: Integração com ferramentas como Zeplin ou FigJam para otimizar o processo de handoff (entrega) para os desenvolvedores.
- **Plugins e Extensões**: Possui uma vasta biblioteca de plugins que automatizam tarefas, como geração de conteúdo fictício ou exportação de recursos.

## 5. Feedback e Iteração
- **Comentários In-line**: Stakeholders podem adicionar feedback diretamente nos protótipos.
- **Histórico de Versões**: Permite revisar e restaurar versões anteriores do design.

O Figma se destaca por sua capacidade de unir design e desenvolvimento, proporcionando um ambiente integrado que facilita a prototipação rápida, colaborativa e eficiente.

Em resumo, iremos utilizar uma ferramenta de design gráfico para montar a parte visual da nossa plataforma. Montaremos o que seria o “front-end” dele, com botões funcionais, fluxo de telas e entre outras funcionalidades para que seja o mais parecido com nossa plataforma possível.
