### ISSUE TITLE
Jigsaw (Web Scraping) - Estudo em grupo

### ISSUE THREAD

**Issue by fdiogo1** [unb-mds/2024-2-Amaiszonia#5]
### Objetivo
* Issue com o objetivo de todos estudarem o tema Web Scraping, visto que o trabalho será baseado em raspagem de dados.
* No método **Jigsaw**, todos contribuem com uma parte do conhecimento. Então, podemos todos ir comentando aqui com bibliotecas, repositórios, dicas, etc...

**Comment by GuilhermeOliveira1327** [comment]
### O que é Web Scraping
Web scraping ou raspagem de dados é o processo de extração automatizada de dados de websites. Utilizando scripts ou ferramentas específicas, é possível coletar informações **publicas** disponíveis em sites, como dados de produtos ou notícias, e armazená-las em formatos como JSON ou CSV. É uma técnica muito usada para coletar dados em larga escala, especialmente em sites que não oferecem uma API oficial garantindo a fidelidade e integridade da informação que foi coletada

### Objetivos
- **Coletar de dados em larga escala:** Facilita a obtenção de grandes quantidades de dados, permitindo análises e visualizações.
- **Monitoramento de preços e concorrência:** Empresas utilizam para acompanhar preços de concorrentes, auxiliando em estratégias de mercado.
- **Pesquisa de mercado:** Coleta dados sobre preferências de clientes e tendências de mercado.
- **Automação de tarefas repetitivas:** Auxilia na coleta de dados como informações de contato e atualizações de sites.

### Exemplos de Aplicação
- **Monitoramento de notícias ambientais:** Permite coletar dados de notícias sobre a Amazônia, gerando insights sobre compromissos ambientais.
- **Análise de redes sociais:** Scraping de dados públicos em postagens e hashtags.
- **Pesquisa científica:** Coleta de dados públicos em larga escala para gerar visualizações e relatórios.

### Web Scraping X API
A raspagem de dados e as APIs (Application Programming Interface) tem o mesmo objetivo, adquirir dados, porém de maneiras diferentes.

Essas tecnologias, quando combinadas, permitem a transação de dados e os disponibilizam em uma interface, como um ERP ou outro sistema. Em outras palavras, a Web Scraping extrai dados de qualquer site por meio de softwares de raspagem, enquanto as APIs oferecem acesso direto aos dados pretendidos.

**Comment by fdiogo1** [comment]
O **BeautifulSoup** é uma biblioteca do Python que pega dados do HTML, mas ela é recomendada apenas para quando não é necessário interagir com a página. Quando vamos interagir com a página é melhor usar o Selenium, que consegue simular ações na página .

**BeautifulSoup:**
 - https://youtu.be/WzUPnQwSQyk?si=pUWEkCCg6eLFh5-t


**Selenium:**
 - https://youtu.be/XLkxOBY965w?si=JNvKSGIgRSxwqXLx


Este abaixo é sobre automação, mas ele utiliza o Selenium também, e mostra o webdriver manager para o Firefox também além do Chrome. 
 - https://youtu.be/8AMNaVt0z_M?si=SLvv-iB-UuwtkJ49


O segundo de Selenium mostra também como procurar por xpath mas o primeiro mostra como procurar com outros dados de referência, que achei melhor caso usássemos vários dados parecidos enquanto o xpath em um dado único que queremos.

**OBS.:** Estudo e texto feito por @GuilhermeDavila
