### ISSUE TITLE
Jigsaw (Docker): Estudo em grupo

### ISSUE THREAD

**Issue by fdiogo1** [unb-mds/2024-2-Amaiszonia#6]

**Comment by bigkaio** [comment]
### O que é o Docker 

  

**Docker** é uma plataforma que facilita a criação, empacotamento e execução de aplicativos em contêineres. Esses contêineres são ambientes isolados que contêm tudo o que um aplicativo precisa para rodar (como código, bibliotecas e configurações), garantindo que ele funcione da mesma forma em qualquer sistema, independentemente das diferenças de configuração. 

  

#### Principais conceitos do Docker: 


- **Contêineres**: São "caixas" leves que isolam o aplicativo e suas dependências. Eles são semelhantes a máquinas virtuais, mas compartilham o mesmo sistema operacional do host, tornando-os mais rápidos e eficientes. 


- **Imagem Docker**: É o modelo base do contêiner. A imagem é criada com tudo o que o aplicativo precisa para rodar. Quando você executa uma imagem, ela se torna um contêiner ativo. 


- **Dockerfile**: É um arquivo que define todas as instruções para construir uma imagem Docker. Nele, o desenvolvedor especifica o sistema base, dependências e comandos necessários para configurar o ambiente do aplicativo. 


- **Docker Hub**: É um repositório onde as imagens podem ser compartilhadas publicamente ou de forma privada. Isso permite que desenvolvedores baixem e compartilhem imagens já configuradas. 

 

### Como o Docker Funciona 
 

O Docker utiliza funcionalidades do kernel do Linux, como **cGroups** e **namespaces**, para isolar processos, permitindo que eles sejam executados de forma independente. Com isso, é possível rodar diferentes aplicativos e processos de forma isolada, aproveitando melhor a infraestrutura disponível e mantendo um nível de segurança semelhante ao de sistemas separados. 


Ferramentas de contêiner, incluindo o Docker, utilizam um modelo de implantação baseado em imagens. Esse modelo simplifica o compartilhamento de aplicativos e de conjuntos de serviços, incluindo todas as dependências, em diversos ambientes. Além disso, o Docker automatiza a implantação dos aplicativos (ou de conjuntos de processos que compõem uma aplicação) dentro desses contêineres. 


Essas tecnologias baseadas em contêineres Linux tornam o Docker uma solução exclusiva e fácil de usar. Elas oferecem aos usuários controle sobre as versões e a distribuição de aplicativos, além de permitir implantações rápidas e acesso fácil aos aplicativos.
