### ISSUE TITLE
Jigsaw (API): Estudo sobre as APIs

### ISSUE THREAD

**Issue by fdiogo1** [unb-mds/2024-2-Amaiszonia#7]
### Objetivo
- O objetivo dessa issue é estudar os principais tópicos de uma API, e como podemos aplicar em nosso projeto.
  - O que é uma API
  - Como utilizar

**Comment by devwallyson** [comment]
## O que é uma API ?
APIs são mecanismos que permitem que dois componentes de software se comuniquem usando um conjunto de definições e protocolos.

## O que significa API?
API significa Application Programming Interface. No contexto de APIs, a palavra Aplicação refere-se a qualquer software com uma função distinta. A interface pode ser pensada como um contrato de serviço entre duas aplicações. Esse contrato define como as duas se comunicam usando solicitações e respostas.

## Como as APIs funcionam?
A arquitetura da API geralmente é explicada em termos de cliente e servidor. A aplicação que envia a solicitação é chamada de cliente e a aplicação que envia a resposta é chamada de servidor.

Existem quatro maneiras diferentes pelas quais as APIs podem funcionar, dependendo de quando e por que elas foram criadas.

### APIs SOAP 
Essas APIs usam o Simple Object Access Protocol (Protocolo de Acesso a Objetos Simples). Cliente e servidor trocam mensagens usando XML. Esta é uma API menos flexível que era mais popular no passado.

### APIs RPC
Essas APIs são conhecidas como Remote Procedure Calls (Chamadas de Procedimento Remoto). O cliente conclui uma função (ou um procedimento) no servidor e o servidor envia a saída de volta ao cliente.

### APIs WebSocket
A [API de WebSocket](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-overview?pg=wianapi&cta=websocketapi) é outro desenvolvimento de API da Web moderno que usa objetos JSON para transmitir dados. Uma API WebSocket oferece suporte à comunicação bidirecional entre aplicativos cliente e o servidor. O servidor pode enviar mensagens de retorno de chamada a clientes conectados, tornando-o mais eficiente que a API REST.

### APIs REST
Essas são as APIs mais populares e flexíveis encontradas na Web atualmente. O cliente envia solicitações ao servidor como dados. O servidor usa essa entrada do cliente para iniciar funções internas e retorna os dados de saída ao cliente. Vejamos as APIs REST em mais detalhes abaixo.

## Quais são os diferentes tipos de API?
As APIs são classificadas de acordo com sua arquitetura e escopo de uso. Já exploramos os principais tipos de arquiteturas de API, agora, vamos dar uma olhada no escopo de uso.

### APIs privadas
Elas são internos a uma empresa e são usadas apenas para conectar sistemas e dados dentro da empresa.

### APIs públicas 
Estas são abertas ao público e podem ser usadas por qualquer pessoa. Pode ou não haver alguma autorização e custo associado a esses tipos de APIs.

### APIs de parceiros 
Estas são acessíveis apenas por desenvolvedores externos autorizados para auxiliar as parcerias entre empresas.

### APIs compostas 
Estas combinam duas ou mais APIs distintas para atender a requisitos ou comportamentos complexos do sistema.

**Comment by renanpariiz** [comment]
# APIs: Mais Informações e Aplicações Práticas

As **APIs** (Application Programming Interfaces) são ferramentas poderosas para integração entre sistemas, permitindo que diferentes aplicações se comuniquem de forma eficiente. Elas são especialmente úteis para trazer dados de uma fonte para um sistema onde esses dados podem ser visualizados ou manipulados.

## Como as APIs São Usadas para Visualizar Dados em um Sistema?

1. **Conexão com Fontes de Dados**:  
   APIs permitem conectar seu sistema a diversas fontes de dados, como bancos de dados, sistemas de CRM, ou serviços externos como Google Maps, Twitter, ou sistemas de pagamento.

2. **Coleta de Dados**:  
   O sistema cliente (sua aplicação) faz uma requisição à API, geralmente usando protocolos como HTTP. A API retorna os dados em formatos estruturados como **JSON** ou **XML**.

3. **Processamento e Transformação**:  
   Após receber os dados, sua aplicação pode processá-los. Por exemplo, filtrar informações relevantes, realizar cálculos, ou transformar os dados para torná-los mais compreensíveis.

4. **Visualização**:  
   Com os dados processados, eles podem ser exibidos usando **gráficos**, **tabelas**, ou outros elementos visuais em uma interface amigável ao usuário.

## Etapas Para Usar APIs no Desenvolvimento de um Sistema de Visualização

1. **Identificação da API Necessária**:
   - Determine qual API pode fornecer os dados que você precisa.
   - Certifique-se de que a API suporta o tipo de integração que você deseja (ex: REST, WebSocket).

2. **Registro e Autenticação**:
   - Muitas APIs públicas e de parceiros exigem que você crie uma conta e obtenha uma **chave de API** para autenticação.

3. **Envio de Requisições**:
   - Configure seu sistema para enviar requisições à API. Por exemplo, se você estiver usando uma API REST, você pode usar métodos HTTP como **GET** (para buscar dados) ou **POST** (para enviar dados).

4. **Manipulação dos Dados Recebidos**:
   - Converta os dados brutos recebidos para o formato necessário e aplique lógica de negócios.

5. **Criação de Dashboards**:
   - Use bibliotecas de visualização de dados como **Chart.js**, **D3.js**, ou ferramentas de desenvolvimento como **Power BI** para criar dashboards interativos.

## Exemplos Práticos

1. **Dashboard Financeiro**:
   - Conecta-se a uma API de mercado financeiro para obter dados em tempo real de ações e exibi-los em gráficos.

2. **Monitoramento de Saúde**:
   - Usa APIs de dispositivos wearable (como Fitbit) para monitorar a atividade física do usuário e apresentar insights.

3. **Gerenciamento de Clientes**:
   - Integração com uma API de CRM para obter dados de clientes e criar relatórios detalhados sobre vendas e interações.

## Ferramentas e Tecnologias Úteis

- **Postman**: Ferramenta para testar APIs e ver como os dados são retornados.
- **Axios/Fetch** (JavaScript): Bibliotecas para fazer chamadas HTTP.
- **Flask/Django** (Python) ou **Express.js** (Node.js): Frameworks para construir backends que consomem APIs.
- **Tableau/Power BI**: Plataformas de BI para visualização avançada de dados.

## Benefícios do Uso de APIs

1. **Automatização**: Reduz a necessidade de entrada manual de dados.
2. **Escalabilidade**: Fácil acesso a grandes volumes de dados em tempo real.
3. **Flexibilidade**: Combinação de diferentes APIs para criar funcionalidades únicas.

---
