### ISSUE TITLE
Jigsaw (nome, logo e identidade visual): Definição

### ISSUE THREAD

**Issue by fdiogo1** [unb-mds/2024-2-Amaiszonia#8]

**Comment by GuilhermeOliveira1327** [comment]
# **Paleta de Cores A+zônia**

## **Cores Principais**

### 1. **Cor da Logo (Verde Principal)**
- **Código:** `#028436`
- Um verde forte e confiável, que será o tom principal do site.

### 2. **Cor de Fundo Principal (Background)**
- **Código:** `#F8F9F8`
- Um branco com um leve toque de cinza esverdeado, proporcionando um fundo claro e amigável.

### 3. **Cor Secundária (Destaques e Botões)**
- **Código:** `#EAF4EA`
- Verde claro e suave, complementar ao verde principal, ótimo para botões secundários ou elementos com destaque sutil.

### 4. **Cor para Texto Principal**
- **Código:** `#333333`
- Cinza escuro, ideal para manter legibilidade no texto principal.

### 5. **Cor para Texto Secundário**
- **Código:** `#666666`
- Cinza médio, para subtítulos ou informações menos relevantes.

### 6. **Cor de Destaque (Chamadas à Ação)**
- **Código:** `#FFD34E`
- Amarelo vibrante, ótimo para botões ou elementos que precisam chamar atenção, como "Compre Agora" ou "Saiba Mais".

### 7. **Cor de Erro ou Alertas**
- **Código:** `#FF6B6B`
- Vermelho suave, para alertas ou mensagens de erro.

---

**Comment by GuilhermeOliveira1327** [comment]
# **Identidade Visual do Site A+zônia**

## **Nome do Site: A+zônia**

O nome **A+zônia** é uma combinação criativa que simboliza a união de inovação e compromisso com a Amazônia. O "A" representa a Amazônia, enquanto o "+" reforça a ideia de progresso e ações positivas para o meio ambiente. 

Esse nome foi escolhido para destacar o propósito do projeto: monitorar e incentivar compromissos ambientais na região da Amazônia Legal.

---

## **Logo**
![Black White Minimalist SImple Monogram Typography Logo (1)](https://github.com/user-attachments/assets/d9627d1f-4db4-4868-8af9-67e58d0da4f9)

A logo do site combina simplicidade e impacto visual. É composta por:

- **Um "A" estilizado**, representando a Amazônia, posicionado de forma destacada.
- **Um "+" ao lado do "A"**, simbolizando ações positivas e progresso.
- **O mapa do Brasil ao fundo**, ressaltando a importância da Amazônia para o Brasil.

A escolha da cor verde para a logo reforça o tema ambiental e a conexão com a natureza.

---

## **Paleta de Cores A+zônia**

### **Cores Principais**

#### 1. **Cor da Logo (Verde Principal)**
- **Código:** `#028436`
- Um verde forte e confiável, que será o tom principal do site.

#### 2. **Cor de Fundo Principal (Background)**
- **Código:** `#F8F9F8`
- Um branco com um leve toque de cinza esverdeado, proporcionando um fundo claro e amigável.

#### 3. **Cor Secundária (Destaques e Botões)**
- **Código:** `#EAF4EA`
- Verde claro e suave, complementar ao verde principal, ótimo para botões secundários ou elementos com destaque sutil.

#### 4. **Cor para Texto Principal**
- **Código:** `#333333`
- Cinza escuro, ideal para manter legibilidade no texto principal.

#### 5. **Cor para Texto Secundário**
- **Código:** `#666666`
- Cinza médio, para subtítulos ou informações menos relevantes.

#### 6. **Cor de Destaque (Chamadas à Ação)**
- **Código:** `#FFD34E`
- Amarelo vibrante, ótimo para botões ou elementos que precisam chamar atenção, como "Compre Agora" ou "Saiba Mais".

#### 7. **Cor de Erro ou Alertas**
- **Código:** `#FF6B6B`
- Vermelho suave, para alertas ou mensagens de erro.

---
